# template for the vue-postgres build job
.build-postgres:
  stage: build
  image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-build-image/master:stable"
  interruptible: true
  retry: 2 # Sometimes our builds are failing due to docker availability, so throwing this in until we know what the issues is
  variables:
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:19.03.12-dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  script:
    - |
      # MLM: Set CI_APPLICATION_TAG to the name of the service, ignore CI_COMMIT_SHA for now
      export CI_APPLICATION_TAG=postgres-${CI_COMMIT_SHA}
      if [[ -z "$CI_COMMIT_TAG" ]]; then
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
        #export CI_APPLICATION_TAG=postgres_${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
      else
        export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE}
        #export CI_APPLICATION_TAG=postgres_${CI_APPLICATION_TAG:-$CI_COMMIT_TAG}
      fi
      if [[ -n "$CI_REGISTRY" && -n "$CI_REGISTRY_USER" ]]; then
        echo "Logging to GitLab Container Registry with CI credentials..."
        docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
      fi
      echo "Building $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"
      docker build -t "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG" -f ./postgres/Dockerfile ./postgres
      echo "Pushing $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"
      docker push "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"

## NOTE: In the future there will be only a build-postgres-review for review, as in production there will be a stable permanent database via cloud SQL
## TODO: build the stable permanent production database to which we will ultimately migrate from v2
# build-postgres-production:
#   extends: .build-postgres
#   rules:
#     - if: $CI_COMMIT_BRANCH == "master"
#   services:
#     - name: docker:19.03.12-dind
#       entrypoint: ["env", "-u", "DOCKER_HOST"]
#       command: ["dockerd-entrypoint.sh"]

build-postgres-review:
  extends: .build-postgres
  rules:
    - if: $CI_MERGE_REQUEST_ID
